### ISSUE TITLE
A value of type 'TouchTrackingBehavior' cannot be added to a collection or dictionary of type 'IList`1'

### ISSUE THREAD

**Issue by drormekorot** [nor0x/TouchTracking.MAUI#2]
MAUI Multi-platform project with .NET 8

Adding `<tt:TouchTrackingBehavior TouchAction="OnTouchEffectAction" />` to any element `Behaviors`  results in an error.
A value of type 'TouchTrackingBehavior' cannot be added to a collection or dictionary of type 'IList`1'.

**Comment by nor0x** [comment]
fixed in https://github.com/nor0x/TouchTracking.MAUI/releases/tag/v0.0.5

thank you @Jeanjean
